sonar.projectKey=Issa-barry_elm-monolith-vue
sonar.organization=issa-barry

sonar.sources=app,resources/js
sonar.tests=tests

sonar.exclusions=public/**,node_modules/**,vendor/**,lang/**,database/migrations/**,tests/e2e/**
sonar.test.exclusions=tests/e2e/**
sonar.cpd.exclusions=tests/**,lang/**,database/migrations/**

sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.sourceEncoding=UTF-8
