sonar.projectKey=Issa-barry_elm-monolith-vue
sonar.organization=issa-barry

sonar.sources=app,resources/js

sonar.exclusions=public/**,node_modules/**,vendor/**,lang/**,database/migrations/**,tests/**,resources/js/**/*.spec.ts,resources/js/**/*.test.ts
sonar.cpd.exclusions=lang/**,database/migrations/**

sonar.php.coverage.reportPaths=coverage/clover.xml
sonar.sourceEncoding=UTF-8
